### PR TITLE
fix copy

### LINKED ISSUE #100: ctrl + c, isn't working correctly
When you will select something else than the full link then you can't copy it.
Blame hup for touching **my code**.

### PR DESCRIPTION
**Pull request by HubertBalcerzak**
Closes #100

### CODE REVIEW

File: gatsby-app/src/components/boxes/AfterPageBox.js [hunk 1]
```diff
@@ -43,11 +43,11 @@ const AfterPageBox = () => {
...
   useEffect(() => {
     const copyText = (event) => {
-      event.preventDefault()
       const select = window.getSelection()
       if (!select.isCollapsed) {
         return
       }
+      event.preventDefault()
       selectLink()
       event.clipboardData.setData('text/plain', resourceLink)
```
Comment (Kuboczoch) [inline gatsby-app/src/components/boxes/AfterPageBox.js:52]: Move event.preventDefault() to the bottom of that function
